### ISSUE TITLE
Error 500 - character conversion failed

### ISSUE THREAD

**Issue by wirbel-at-vdr-portal** [MarkusEh/vdr-plugin-live#10]
With tntnet-3 the plugin fails to show records.

console message:
"WARN tntnet.worker - http-Error: 500 character conversion failed"

Solution, add in pages/recordings.ecpp:308

#if TNTVERSION >= 30000
++            shortDescr = CorrectNonUTF8(&shortDescr); // cleanup invalid UTF-8 characters
                description = CorrectNonUTF8(&description); // cleanup invalid UTF-8 characters
                                                            // Tntnet30 throw: tntnet.worker - http-Error: 500 character conversion failed
#endif

**Comment by kfb77** [comment]
Hi wirbel,
I am the contributor for the tntnet30 patches. I agree to your issue and will add your patch

**Comment by kfb77** [comment]
fixed with commit https://github.com/MarkusEh/vdr-plugin-live/commit/bff94e46e3ef94aa72f0311d970fa2a4c1eb8040
