### ISSUE TITLE
EPG Info broken

### ISSUE THREAD

**Issue by kfb77** [MarkusEh/vdr-plugin-live#13]
With this commit https://github.com/MarkusEh/vdr-plugin-live/commit/b0459ffa85b595d79ce3dee14d79152b0bad153f the EPG subwindow position is broken.
Opening EPG Info at the top of the channel or timer list works, With each line down of the list, the EPG windows opens more on the buttom of the screen or do no longer open.

**Comment by heifisch** [comment]
This patch solves the problem.

[InfoWin_Position_01.txt](https://github.com/MarkusEh/vdr-plugin-live/files/6565904/InfoWin_Position_01.txt)

**Comment by tmn505** [comment]
Does not help. The EPG for first two rows seem to be okay, slightly below, but for next subsequent rows is not visible (the subwindow appears down below). Tried it out in Firefox and Opera. It happens with b0459ff reverted and without.

**Comment by heifisch** [comment]
For me it works with Firefox and Chromium without errors.

According to here:
https://www.mediaevent.de/javascript/window-browserfenster.html

the position of the cursor was derived from the position of the mouse in the document before the patch, but from the position of the mouse browser window after the patch.

The changed offset values should not lead to malfunctions.

**Comment by tmn505** [comment]
Sorry, indeed, the patch fixes the problem. I had applied unrelated patch and build with the thought in mind that it was correct one.

**Comment by MarkusEh** [comment]
Fixed in v3.0.9.
You might need to clear the browser cache (css files).
