### ISSUE TITLE
no close buttom of recording details from very long recording names

### ISSUE THREAD

**Issue by kfb77** [MarkusEh/vdr-plugin-live#16]
I have a minor issue of the recording details info box for very long recording names.
You can reproduce it if you name a recording "Rückkehr in die Antarktis Doku-Reihe, USA 2019 Altersfreigabe: ab 12 (WH vom Dienstag, 15.06.2021, 20:15 Uhr)" and click on the recording for details. The info box opens with a two lines header and no "x" to close the window. Please excuse: html is not my core competence, so only a issue and no PR.

**Comment by MarkusEh** [comment]
Hi,

This is fixed in latest git.

**Comment by kfb77** [comment]
successfully tested
Thanks, I close the issue.
