### ISSUE TITLE
Support for tvscraper artwork

### ISSUE THREAD

**Issue by Dis90** [MarkusEh/vdr-plugin-live#19]
Can you add support for tvscraper (https://github.com/vdr-projects/vdr-plugin-tvscraper) to provide artwork for EPG and recordings?

**Comment by MarkusEh** [comment]
Hi,

Very good suggestion, but I don't have time for that :( .
Can you create a pull request?

~Markus

**Comment by Dis90** [comment]
My time is also very limited at the moment :D 
I'll try to make it when I have some time :)

**Comment by Dis90** [comment]
I tried few different things but couldn't get it properly working. Problem is that pageelems.ecpp doesn't have whole event or recording which is needed for tvscraper.

If someone wants to try make it working, sample code for tvscraper can be found https://github.com/Dis90/vdr-plugin-vnsiserver/blob/tvscraper_backendresume/vnsiclient.c#L2747
scraper2vdr.h is also needed https://github.com/Dis90/vdr-plugin-vnsiserver/blob/tvscraper_backendresume/scraper2vdr.h

I copied it somewhere, can't remember where.

**Comment by MarkusEh** [comment]
Hi Dis90,

There is a plugin interface in VDR, where live can communicate with tvscraper.
This is how VDR skins get the images.
I don't know the details, but you can ask here https://www.vdr-portal.de/forum/index.php?board/80-software/ for help.

**Comment by MarkusEh** [comment]
Done with v3.1.3.
