### ISSUE TITLE
can't compile vdr-plugin-live-3.0.4 with new version of tntnet and cxxtools-3.0.0

### ISSUE THREAD

**Issue by martinkg** [MarkusEh/vdr-plugin-live#2]
Hi,

when compiling vdr-plugin-live-3.0.4 on Fedora 33 with the new version of tntnet-3.0.0 and cxxtools-3.0.0
i get the following error messages:

```
recordings.ecpp: In member function 'virtual unsigned int {anonymous}::_component_::operator()(tnt::HttpRequest&, tnt::HttpReply&, tnt::QueryParams&)':
recordings.ecpp:76:6: error: 'deletions_type' has not been declared
   76 | for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {
      |      ^~~~~~~~~~~~~~
recordings.ecpp:76:61: error: 'it' was not declared in this scope; did you mean 'int'?
   76 | for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {
      |                                                             ^~
      |                                                             int
recordings.ecpp: In member function 'virtual unsigned int {anonymous}::_component_::recordings_item_type::operator()(tnt::HttpRequest&, tnt::HttpReply&, tnt::QueryParams&)':
recordings.ecpp:250:8: error: 'path_type' has not been declared
  250 |   for (path_type::const_iterator i = path.begin(); i != path.end(); ++i) {
      |        ^~~~~~~~~
recordings.ecpp:250:52: error: 'i' was not declared in this scope
  250 |   for (path_type::const_iterator i = path.begin(); i != path.end(); ++i) {
      |                                                    ^
make[1]: *** [Makefile:34: recordings.o] Error 1
make: *** [Makefile:191: pages] Error 2
```
so that vdr-live recognizes the new version tntnet-3, i use the attached patch. 
[vdr-live-tntnet3-Makefile.patch.txt](https://github.com/MarkusEh/vdr-plugin-live/files/5938547/vdr-live-tntnet3-Makefile.patch.txt)
[cxxtools-3.0-1.fc33.src.rpm](https://martinkg.fedorapeople.org/Packages/test/cxxtools-3.0-1.fc33.src.rpm)
[tntnet-3.0-1.fc33.src.rpm](https://martinkg.fedorapeople.org/Packages/test/tntnet-3.0-1.fc33.src.rpm)

I asked about this bug on the Fedora development mailing list and received the following response: 

> firstly "ecppc" program (in tntnet) converts *.ecpp file to
*.cpp file, then converted .cpp file is compiled by g++.  recordings.cpp
generated with ecppc (in tntnet 2.2.1) actually contains the definition for
> 
> type "deletions_type" .
> 
> I guess in *.ecpp file, "deletions_type" means the type of "deletions" variable, 
so "ecppc" 2.2.1 defines "deletions_type" as such in generated cxx source.
> 
> So I guess ecppc in tntnet 3 is somehow broken. I guess you can check the actually generated
"recordings.cpp" file. (Note that generated "recordings.cpp" contains something like
> 
> ...
>  #line 1 "recordings.ecpp"
> 
> so while g++ actually compiles recordings.cpp, the error messages looks like errors
happened on the original .ecpp file.)

[root@fc33 built_with_tntnet2]# grep deletions_type *
`recordings.cpp:typedef std::vector<string> deletions_type;
 recordings.cpp:deletions_type deletions;
 recordings.cpp:for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {
 recordings.ecpp:for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {`

[root@fc33 built_with_tntnet3]# grep deletions_type *
`recordings.cpp:for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {
 recordings.ecpp:for (deletions_type::const_iterator it = deletions.begin(); it != deletions.end(); ++it) {`

it would be nice if vdr-live could also compile with the new versions of cxxtools / tntnet-3.

**Comment by kfb77** [comment]
Have you testet this solution ?
I think there is much more to do to get live plugin running with Tntnet3.0
I have some patches to get more function running, but still have a crash in the recording list.
@MarkusEh : If you make a branch "Tntnet30" I can pull my patches and this can be a base for future work.

**Comment by martinkg** [comment]
> Have you testet this solution ?
> I think there is much more to do to get live plugin running with Tntnet3.0
> I have some patches to get more function running, but still have a crash in the recording list.
> @MarkusEh : If you make a branch "Tntnet30" I can pull my patches and this can be a base for future work.

I have included the patch for the detection of the new tntnet and as a test, the two lines
```
typedef std :: vector <string> deletions_type;
deletions_type deletions;
```
in the recordings.cpp and executed a make, then I got this:
 
[martin @ fc34 vdr-plugin-live-3.0.4] $ vim pages / recordings.cpp
[martin @ fc34 vdr-plugin-live-3.0.4] $ make
CC pages / recordings.o
page_exit.eh: In the member function "virtual unsigned int {anonymous} :: _ component _ :: operator () (tnt :: HttpRequest &, tnt :: HttpReply &, tnt :: QueryParams &)":
page_exit.eh:246:16: Error: redeclaration of »deletions_type deletions«
Compilation ended because of "-Wfatal-errors".
make [1]: *** [Makefile: 34: recordings.o] Error 1
make: *** [Makefile: 191: pages] Error 2
 
Unfortunately, I am not a programmer, but I can try to integrate patches and test them with them.

**Comment by kfb77** [comment]
Try my test branch for Tntnet30: https://github.com/kfb77/vdr-plugin-live/tree/Tntnet30
It compiles under Ubuntu with the current clone of Tntnet 30 git (maybe also unter Fedora, I dont know) but notice: list the recordings will result in a VDR crash

**Comment by kfb77** [comment]
One more comment:
"vim pages / recordings.cpp"
You may not edit pages/*.cpp files, type are build from the ecpp preprocessor based on *.ecpp files.
Maybe we should discuss the details in the vdr-portal forum, this is not part of the issue.

**Comment by martinkg** [comment]
> Try my test branch for Tntnet30: https://github.com/kfb77/vdr-plugin-live/tree/Tntnet30
> It compiles under Ubuntu with the current clone of Tntnet 30 git (maybe also unter Fedora, I dont know) but notice: list the recordings will result in a VDR crash

Yes it compiles on Fedora also.
> One more comment:
"vim pages / recordings.cpp"
You may not edit pages/*.cpp files, these are build from the ecpp preprocessor based on *.ecpp files.
Maybe we should discuss the details in the vdr-portal forum, this is not part of the issue.

Yes, I know that, i only added the lines for testing purposes. I'll open a thread on the vdr portal once I've installed the vdr-live plugin.

**Comment by MarkusEh** [comment]
Hi,
I created Tntnet30 and invited kfb77. So you can directly commit your patches.

**Comment by kfb77** [comment]
@MarkusEh: Thx for access to your repository
@martinkg: The crash is fixed, you can continue your tests

**Comment by kfb77** [comment]
Branch Tntnet30 compiles now with Tntnet30.
Before merge much more testing is necessary but the original issue is fixed.
I close this issue.
