### ISSUE TITLE
vdr-plugin-live stop building with make 4.4

### ISSUE THREAD

**Issue by uwe5** [MarkusEh/vdr-plugin-live#33]
Hi,

vdr-plugin-live stop building and due to make getting stuck in loop
and complaining with: 

`server1:/usr/local/src/vdr/PLUGINS/src/live # make -d
GNU Make 4.4
Built for x86_64-suse-linux-gnu
Copyright (C) 1988-2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>

This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Reading makefiles...
Reading makefile 'Makefile'...
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Reading makefile 'global.mk' (search path) (no ~ expansion)...
Makefile:27: not recursively expanding CFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:28: not recursively expanding CXXFLAGS to export to shell function
Makefile:27: not recursively expanding CFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:27: not recursively expanding CFLAGS to export to shell function
Makefile:44: not recursively expanding CXXFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:44: not recursively expanding CXXFLAGS to export to shell function
Makefile:27: not recursively expanding CFLAGS to export to shell function
Makefile:44: not recursively expanding CXXFLAGS to export to shell function
Makefile:44: not recursively expanding CXXFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Reading makefile '.dependencies' (search path) (don't care) (no ~ expansion)...
Updating makefiles....
 Considering target file 'Makefile'.
  Looking for an implicit rule for 'Makefile'.
  Trying pattern rule '%: %.o' with stem 'Makefile'.
Directory . cache invalidated (count 1 != command 19)
  Trying implicit prerequisite 'Makefile.o'.
  Not found 'Makefile.o'.
  Trying pattern rule '%: %.c' with stem 'Makefile'.
  Trying implicit prerequisite 'Makefile.c'.

...

 No need to remake target 'global.mk'.
 Considering target file '.dependencies'.
   Pruning file 'Makefile'.
  Finished prerequisites of target file '.dependencies'.
  Prerequisite 'Makefile' is newer than target '.dependencies'.
 Must remake target '.dependencies'.
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:54: not recursively expanding CXXTOOLVER to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:54: not recursively expanding CXXTOOLVER to export to shell function
Makefile:86: not recursively expanding DEFINES to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:43: not recursively expanding TNTVERSION to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:54: not recursively expanding CXXTOOLVER to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Directory pages cache invalidated (count 19 != command 20)
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:54: not recursively expanding CXXTOOLVER to export to shell function
Makefile:43: not recursively expanding TNTVERSION to export to shell function
Makefile:54: not recursively expanding CXXTOOLVER to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:43: not recursively expanding TNTVERSION to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:66: not recursively expanding CXXFLAGS to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function
Makefile:14: not recursively expanding HAVE_PCRE2 to export to shell function
Makefile:62: not recursively expanding LIBS to export to shell function
Makefile:18: not recursively expanding PKGCFG to export to shell function

...`

Hints:
[https://lists.gnu.org/archive/html/info-gnu/2022-10/msg00008.html](url)

[https://lists.opensuse.org/archives/list/factory@lists.opensuse.org/thread/FPNDORIL6NDJD3HFQ76LQBIRBCWVG6TV/](url)

[live-make.tar.gz](https://github.com/MarkusEh/vdr-plugin-live/files/10327147/live-make.tar.gz)

**Comment by madmartin** [comment]
Hi, 

I can confirm this on gentoo linux. Downgrade make to version 4.3 solved it.

**Comment by MarkusEh** [comment]
Can you provide a PR/patch?

**Comment by madmartin** [comment]
@MarkusEh I hope I found a solution. Will do some more tests tomorrow, if successful I place a PR here.

**Comment by madmartin** [comment]
@MarkusEh @uwe5 see PullRequest #35

**Comment by MarkusEh** [comment]
pull request merged
