### ISSUE TITLE
Repository description is wrong

### ISSUE THREAD

**Issue by madmartin** [MarkusEh/vdr-plugin-live#34]
The current repository description is

`Mirror of https://projects.vdr-developer.org/git/vdr-plugin-live.git and a Collection of Patches from https://www.vdr-portal.de/`

which is misleading, because https://projects.vdr-developer.org does not exist any more. 
Please edit to something meaningful.

**Comment by MarkusEh** [comment]
Changed

**Comment by madmartin** [comment]
Excellent, thanks!
