### ISSUE TITLE
Syntax Error in line 11 of Makefile with GNU Make 4.2.1

### ISSUE THREAD

**Issue by seahawk1986** [MarkusEh/vdr-plugin-live#36]
Hello,
I get an syntax error if I try to build the latest version of vdr-plugin-live on Ubuntu 20.04 with GNU Make 4.2.1:
```shell
$ git clone https://github.com/MarkusEh/vdr-plugin-live
Klone nach 'vdr-plugin-live' …
remote: Enumerating objects: 9096, done.
remote: Counting objects: 100% (1389/1389), done.
remote: Compressing objects: 100% (364/364), done.
remote: Total 9096 (delta 1021), reused 1348 (delta 1016), pack-reused 7707
Empfange Objekte: 100% (9096/9096), 5.89 MiB | 2.97 MiB/s, fertig.
Löse Unterschiede auf: 100% (6735/6735), fertig.
$ cd vdr-plugin-live
$ make
Makefile:11: *** Nicht beendeter Aufruf der Funktion „shell“: „)“ fehlt.  Schluss.
```
According to https://stackoverflow.com/a/53837400 the hashtag needs to be escaped (which works with Make 4.2.1), but this doesn't work with GNU Make 4.3 because the escaped hashtag is forwarded to awk:
```shell
$ make
awk: cmd. line:1: warning: regexp escape sequence `\#' is not a known regexp operator
```

**Comment by madmartin** [comment]
Hello @seahawk1986 ,

I have tested my PullRequest #35  with GNU make versions 4.3 and 4.4 and both worked.
It was merged yesterday 5-1-2023 around 19:00 CET.
Can you please look if your "git clone" has been done with the most recent commits?

Bye
Martin

**Comment by seahawk1986** [comment]
Looks good to me:
````shell
$ git show
commit c43216eed5e5eb93672e429d45ec325e25e4d952 (HEAD -> master, origin/master, origin/HEAD)
Merge: 2c18a99 a3671a5
Author: Markus <43744317+MarkusEh@users.noreply.github.com>
Date:   Wed Jan 4 18:49:07 2023 +0100

    Merge pull request #35 from madmartin/fix-makefile-grep-warning
    
    Makefile: remove grep warning and fix build with make-4.4

$ make
Makefile:11: *** Nicht beendeter Aufruf der Funktion „shell“: „)“ fehlt.  Schluss.
````
The issue seems to exists with GNU Make < 4.3 (same problem with GNU Make 3.81 in an old Ubuntu 14.04 VM I had lying around) - I can work around this with a patch for the packages, but if there is a better way that doesn't break it for others still using older make versions I would prefer that.

**Comment by MarkusEh** [comment]
Can someone provide a patch, so it works with GNU Make < 4.3 as well as with GNU Make >= 4.3 ?

**Comment by MarkusEh** [comment]
Should be fixed in git.
Please test

**Comment by MarkusEh** [comment]
See also 
https://www.vdr-portal.de/forum/index.php?thread/135423-live-3-1-11/&postID=1356105#post1356105
Solved with TomJoads proposal:
HASH := \#

VERSION := $(shell grep '$(HASH)define LIVEVERSION ' setup.h | awk '{ print $$3 }' | sed -e 's/[";]//g')
