### ISSUE TITLE
Add web based channel list editor

### ISSUE THREAD

**Issue by M-Reimer** [MarkusEh/vdr-plugin-live#38]
The whole "channels.conf" concept was and is something I never liked about VDR.

What VDR really is missing is some kind of user friendly way to edit the channel list. And I would prefer being able to do it in a web browser. So at least for me it seems like integrating one inside the live plugin would be a perfect fit.

**Comment by MarkusEh** [comment]
Can you provide a PR?

**Comment by M-Reimer** [comment]
No, sorry. I can't. I just wanted to have this noted as an idea for possible future feature addtions.

**Comment by MarkusEh** [comment]
My channels.conf has about 2000 lines.
Web UI might be possible, but not easy to implement
From time to time I sort with vi ...

**Comment by M-Reimer** [comment]
Actually I think a "two column layout" could be best. Two lists which basically sync themselves. This would allow to have one list scrolled to the top (where channels are properly sorted) while scrolling the second one to wherever the "source channels" are (auto-added by VDR, for example). And then drag and drop the "new channels" to the "sorted region".

It is possible to do sorting with any kind of text editor. And some VDR users seem to really like this. But I just totally hate this and it is unfeasible for any "average user" to do this. And it is actually pretty easy to corrupt the channels.conf and make VDR no longer start at all.

I have one friend where I have VDR installed and THE thing, that I get asked EVERY TIME is that he wants some nicer way to organize his channels.

**Comment by MarkusEh** [comment]
Ich werde das nicht implementieren, sorry :(

**Comment by M-Reimer** [comment]
Schade. Hätte ein Feature sein können von dem echt viele profitieren könnten. So wie Kanalmanagement aktuell am VDR läuft ist es halt Kacke.

**Comment by M-Reimer** [comment]
Wenn jemand den "Server seitigen" Teil zumindest zum Teil übernehmen könnte, dann wäre zu ggf. für ein Teamprojekt dazu zu haben. Ich werde mich nicht in tntnet einarbeiten (meiner Meinung nach tote Technik) aber wenn eine Schnittstelle da wäre um vom Browser aus eine Kanalliste zu holen und gezielt einen Kanal (anhand der Channel-ID?) an eine neue Position (Relativ zu einer anderen Channel-ID?) zu schieben, dann könnte ich den "Web-Teil" dafür bauen.

**Comment by MarkusEh** [comment]
SVDRPSEND ?
Da gab es doch auch plugins (?).

**Comment by M-Reimer** [comment]
SVDRPSEND bringt nur nix wenn man vor hat die Kanalliste im Browser anpassen zu können.

Im Prinzip bräuchte man zwei Schnittstellen. Auf der Basis könnte man dann mit "reiner Web-Entwicklung" (inklusive Nutzung passender Libraries) aufsetzen.

**Schnittstelle zum "Holen" des aktuellen Zustands**

Könnte z.B. einfach die komplette Kanalliste als JSON formatiert zum Browser schicken. Das wird benötigt um eine Kanalliste "vorzubestücken".

**Schnittstelle zum "Schieben" **

Diese Schnittstelle müsste zumindest zwei Parameter akzeptieren. Den Kanal (Kanal-ID) der verschoben werden soll und eine Position (Ziel-Kanal-ID). Dazu dann noch entweder die Info ob "davor" oder "danach" oder man würde das halt so lösen das der Kanal an die erste Position kommt wenn keine "Ziel-Position" gegeben wird. In dem Fall wird dann immer hinter die gegebene "Referenz" geschoben.

Was diese Schnittstelle auch rückmelden muss, ist, ob der Verschiebevorgang erfolgreich war. Der VDR lässt nämlich in bestimmten Situationen kein Schieben zu.


Auf Server-Seite würde ich mir das dann so vorstellen das man zwei gleiche Kanallisten nebeneinander rendert und dann sowohl innerhalb der gleiche Liste als auch zwischen den Listen ein Schieben per Drag&Drop zulässt. Das erlaubt dem Benutzer eine Liste auf die "Quellposition" und eine auf die "Zielposition" zu scrollen und dann einfach von links nach rechts (oder umgekehrt) die Kanäle einfach "rüberzuschubsen". Wenn bei der Anfrage der Web-Schnittstelle "Erfolg gemeldet" wird, dann wird der entsprechende Schiebevorgang auch im Browser durchgeführt (auf beiden Listenseiten) um die neue Situation zu repräsentieren.
