### ISSUE TITLE
Add input field for native svdrp commands

### ISSUE THREAD

**Issue by michhey** [MarkusEh/vdr-plugin-live#4]
Would it be possible to add an input field somewhere in live for executing SVDRP commands (such as hitk Power or mesg "hello")?
vdradmin has this functionality and it is really usefull if you don't have access to a shell console but can access the live web page.

**Comment by MarkusEh** [comment]
Can you create a pull request?

**Comment by michhey** [comment]
I'll try to implement it and create a pull request. May take a while...

**Comment by MarkusEh** [comment]
Feature request, I will not implement this
