### ISSUE TITLE
Add a "headless only" mode

### ISSUE THREAD

**Issue by M-Reimer** [MarkusEh/vdr-plugin-live#40]
"Live" has several buttons which only make sense if you are remote controlling a VDR system which also has some kind of output plugin installed. This includes stuff like playback of a recording in the recording list or tuning to a channel.

I think it would be useful to allow disabling/hiding all this either by a setup parameter or probably even (if possible) by auto detecting that the VDR system does not have any output available.

**Comment by MarkusEh** [comment]
Is available in git. Automatic detection if primary device has mpg decoder. Please test. 

Still, you should apply Klaus patch from https://www.vdr-portal.de/forum/index.php?thread/135519-server-ohne-ausgabeplugin-kanal-%C3%A4ndern-f%C3%BChrt-zu-error-video-data-stream-broken/ , if you have such a server.
