### ISSUE TITLE
Plugin crashes if locale not installed

### ISSUE THREAD

**Issue by bviefhues** [MarkusEh/vdr-plugin-live#43]
The plugin crashes VDR if the locale VDR is started with is not installed on the Linux system.

Reproduce:
- Install Debian Bookworm with only `en_US.utf8` selected
- Start VDR with live plugin with this environment:
```sh
LANG=de_DE.UTF-8
VDR_LANG=de_DE.UTF-8
LC_ALL=de_DE.UTF-8
```
- VDR crashes on start with these journal messages:
```sh
[40535] loading plugin: /usr/local/lib/vdr/libvdr-live.so.2.6.3
terminate called after throwing an instance of 'std::runtime_error'
  what():  locale::facet::_S_create_c_locale name not valid
```

The crash does not occur any more if `de_DE.utf8` is installed via `dpkg-reconfigure locales`.

Would be great if the plugin would fallback to English if the locale is not installed.

**Comment by MarkusEh** [comment]
We might also go for a better error message.
If LANG=de_DE.UTF-8 and the plugin uses another locale, this will be at first (most likely) not detected.
And if it is detected, the user will think he detected a bug or missing functionality.

Can you provide a patch to fix this?

**Comment by MarkusEh** [comment]
Thank you for providing the error report.
I added a note to README, so I hope others will find the solution faster.

I didn't find an easy way to improve the code, but patches are still welcome.
I think the code is in "live.cpp",
`
const std::locale g_locale = std::locale("");
const std::collate<char>& g_collate_char = std::use_facet<std::collate<char> >(g_locale);
`

I close this issue, as I plan no further improvement.
