### ISSUE TITLE
Searchtimer are not found in webif when id >1000

### ISSUE THREAD

**Issue by MegaV0lt** [MarkusEh/vdr-plugin-live#44]
Searchtimer are not found in webif when id >1000.
Problem is the . (1.000) in the url. Sample screenshot:
![Auswahl_227](https://github.com/MarkusEh/vdr-plugin-live/assets/2804301/58d80212-eaf2-4e51-bbb2-ed6c59c37ea4)

When i remove the dot the Timer is shown

**Comment by MarkusEh** [comment]
fixed in git. Please test

**Comment by MegaV0lt** [comment]
Thank you for the fix. I will test when the package is available in yaVDR

**Comment by MarkusEh** [comment]
Dann solltest du seahawk1986 bitten, das in yaVDR zu übernehmen ...

**Comment by MarkusEh** [comment]
Die Navigation von searchtimers.html "Suchtimer" nach edit_searchtimer.html?searchtimerid=1023 "Suchtimer bearbeiten" habe ich korrigiert, das sollte jetzt gehen.


Die Naviagation von timers.html "Timer" zu "Suchtimer bearbeiten" und von timerconflicts.html "Timer-Konflikte" zu "Suchtimer bearbeiten" habe ich nicht geändert. Tritt der Fehler da auch auf?

**Comment by MegaV0lt** [comment]
Vielen Dank. Ich kann das erst ab Montag testen wenn ich zu hause bin

**Comment by MegaV0lt** [comment]
Suchtimer der grüne button bearbeiten funktioniert bei ID > 1.000 auch nicht
![Auswahl_231](https://github.com/MarkusEh/vdr-plugin-live/assets/2804301/f63a4780-f2a1-4982-b871-8c7dfa595992)

Timerkonflikte funktioniert bei normalen Timern, da da eine andere ID verwendet wird. Suchtiimerkonflikte konnte ich noch nicht testen. Vermute aber, dass es da auch so ist mit dem '.'
