### ISSUE TITLE
[Feature request] Better optical sepaeration of inactive timers

### ISSUE THREAD

**Issue by MegaV0lt** [MarkusEh/vdr-plugin-live#45]
Inactive timers should be drawn in grey to indicate the status better
![Auswahl_233](https://github.com/MarkusEh/vdr-plugin-live/assets/2804301/22f93fa4-4726-4468-b02a-6da15f75046f)

**Comment by MarkusEh** [comment]
Na ja, es gibt ja den dicken Pfeil links. Aber klar, besser wäre es schon.
Magst Du einen Patch bauen und im VDR Portal posten?

Wenn Die User vom VDR Portal den Patch gut finden, werde ich ihn auch übernehmen.

**Comment by MegaV0lt** [comment]
Wenn ich wieder Zeit habe schau ich mal rein.

**Comment by flell** [comment]
In meinem [grayedlistings-Branch](https://github.com/flell/vdr-plugin-live/commits/grayedlistings) liegen zwei Commits, die das Feature liefern.

Ich hatte auch versucht das CSS an der Stelle etwas eleganter zu konsolidieren (Styling über tr-Reihe statt für jeden einzelnen td-Tag in der Reihe), das dafür notwendige ```border-collapse:collapse``` in table.listings lässt aber oben den Header aus dem Leim gehen (siehe Screenshot rechts).

Man könnte auch /img/bg_line.png auf einen CSS-Gradient umstellen (```background: linear-gradient(0deg, #e9efff 1px, #ffffff 6px) bottom;```), dann muss man aber bei allen Themes nachziehen.

Hat eigentlich jemand eine Ahnung, ob die nicht-marine-Themes überhaupt genutzt werden?

![bg_inactive3](https://github.com/MarkusEh/vdr-plugin-live/assets/152076319/f8298a87-12d7-438e-81e7-38ef63c0f6e1)

**Comment by flell** [comment]
Eben noch um einen Commit für die timers.ecpp ergänzt.
War mir gar nicht bewusst, dass es @MegaV0lt ursprünglich darum ging. :innocent:

**Comment by MegaV0lt** [comment]
Mit dem grauen Hintergrund kann man leben. 
Besser wäre es, die Schrift in dunkelgrau anzuzeigen. Bei dem grauen Hintergrund könnte man meinen die Zeile ist ausgewählt...

**Comment by MarkusEh** [comment]
Ist in 3.3.10
