### ISSUE TITLE
streaming a stored record won't support jump back/forward in difference to vdradmin-am

### ISSUE THREAD

**Issue by pbiering** [MarkusEh/vdr-plugin-live#55]
Have I missed a settings toggle somewhere or is streaming of a stored record not supporting jump back/forward so far?

Can this be related to how the stream is accessed?

vdradmin.m3u8 (using streamserver port directly, jump back/forward working well in vlc):
```
http://192.168.x.x:3000/20**:216929****.rec
```

playlist.m3u8 (vlc is not able to jump forward/back)
```
http://192.168.x.x:8008/recstream.html?recid=recording_********52139A68D
77B23BD********
```
Thank you for any hints.

**Comment by nobanzai** [comment]
Same here.

**Comment by MarkusEh** [comment]
I recommend a new thread in vdr-portal.
I cannot help with this issue.

**Comment by MarkusEh** [comment]
Fixed

**Comment by pbiering** [comment]
btw: HISTORY file misses updates, is it stale nowadays?

**Comment by MarkusEh** [comment]
Define stale

**Comment by nobanzai** [comment]
Works perfectly - thx!

**Comment by pbiering** [comment]
> Define stale

while tag is on 3.3.5, HISTORY stopped on 3.2.0

But anyhow, thank you very much for implementation, works now as expected!
