### ISSUE TITLE
Validation error at create timer discards all fields

### ISSUE THREAD

**Issue by maazl** [MarkusEh/vdr-plugin-live#56]
When a validation error occurs while crating a new timer all input fields are cleared to their default value.
If the title field is empty (likely for channels w/o EPG) and save is pressed an error occurs (correctly), but at the same time all (other?) input fields are reset to their default value when creating a new timer. The latter is unexpected and error prone. The user might not notice the change and create a timer that records some arbitrary channel immediately.

![Bildschirmfoto_2023-12-31_10-11-24](https://github.com/MarkusEh/vdr-plugin-live/assets/12786145/b765526a-5baa-452a-9d95-4dff08518b68)

A similar issue applies to existing timers. When editing causes a validation error (less likely, of course), all possibly changed fields are reset to the last saved value.

I will try to provide a fix in the next week.

**Comment by maazl** [comment]
Added PR #58

**Comment by MarkusEh** [comment]
Fixed in git
