### ISSUE TITLE
Compiler error with Debian Buster

### ISSUE THREAD

**Issue by maazl** [MarkusEh/vdr-plugin-live#57]
```c++
In file included from tools.h:24,
                 from live.cpp:10:
stringhelpers.h: In member function ‘cToSv::operator std::string_view() const’:
stringhelpers.h:640:54: error: call of overloaded ‘cSv(const cToSv&)’ is ambiguous
     operator std::string_view() const { return (cSv)*this; }
```

The problem is caused by the redundant conversion operator in the last line:
```c++
class cToSv {
  public:
    cToSv() {}
// not intended for copy
// you can copy the cSv of this class (from  operator cSv() )
    cToSv(const cToSv&) = delete;
    cToSv &operator= (const cToSv &) = delete;
    virtual ~cToSv() {}
    virtual operator cSv() const = 0;
    operator std::string_view() const { return (cSv)*this; } // <--- HERE
};
```

cSv _is_ std::string_view, so the second conversion operator is superfluous.

**Removing the last operator fixes the issue.**

**Comment by MarkusEh** [comment]
I don't see this error :(
does it help to change the line to 
    operator std::string_view() const { return cSv(*this); }
?

**Comment by maazl** [comment]
No the latter change makes no difference. (Just another syntax)

I think this is related to the gcc version 8.3.0.
The overload resolution rules are complicated and have slightly changed over time. Maybe this ambiguity has been resolved. Maybe it is just a gcc bug.

But from my point of view the line is completely unnecessary. It compiles and works without it, at least with gcc 8.3.
The line with `operator cSv() const` already covers the conversion to `string_view`. And the implementation of `operator string_view() const` just calls `operator cSv() const` anyway.

**Comment by MarkusEh** [comment]
fixed in git, I removed this line.
