### ISSUE TITLE
Could not play video in Browser

### ISSUE THREAD

**Issue by obrain17** [MarkusEh/vdr-plugin-live#62]
First of all thank you for this very useful plugin. I am using it in connection with yaVDR ansible (headless).

I just have installed new version 3.3.7 because I wanted to have the benefit of playing also recordings in the brower,

```
vdr-plugin-live-ng/noble,now 3.3.7-0yavdr0~noble amd64  [installiert]
```

Unfortunately playing in browser does not work anymore at all and some seconds after start I get the error:
```
              Could not play video
   There was a problem trying to load the video
Error code: hls:networkError_manifestLoadTimeOut
```

With my formerly installed version (3.3.5 ?) it worked, but also there only with Firefox but in Chrome/Edge only for some channels (e.g. ZDF)

I now tried Firefox in Windows 11, Ubuntu 24 and Android 14, but always get the same error when accessing this URL:
```
http://yavdr:8008/stream.html?channelid=S19.2E-1-1019-10301
```

Maybe you can help me ?

**Update:**
I just found there was a symlink to `/etc/vdr/plugins/live/ffmpeg.conf` but the file was not existing there. 
I copied it from github and now both recordings and channels can be played with Firefox.
Maybe some settings need to be changed for other browsers, but this has low priority, I am happy with Firefox.

**Comment by MarkusEh** [comment]
The ffmpeg commands are now in /etc/vdr/plugins/live/ffmpeg.conf , out of security considerations.
The yaVDR debian package should install this file (if not, you can file a bug in yaVDR).

You can change /etc/vdr/plugins/live/ffmpeg.conf , if other ffmpeg commands work better for you.
